const usersData = [
  {stt: 0, nickname: 'Khang đẹp trai pro 98 pt', score: '900', time: '30'},
  {stt: 1, nickname: 'Phạm Huy Minh', score: '890', time: '25'},
  {stt: 2, nickname: 'Vũ Hoàng Đức Hiếu', score: '890', time: '25'},
  {stt: 3, nickname: 'Trinh Ngoc Khang', score: '700', time: '25'},
  {stt: 4, nickname: 'Phùng Văn Hoàng', score: '700', time: '25'},
  {stt: 5, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 6, nickname: 'Vũ Xuân', score: '700', time: '25'},
  {stt: 7, nickname: 'Vũ Hoàng Đức Hiếu', score: '700', time: '25'},
  {stt: 8, nickname: 'Vũ Hoàng Đức Hiếu', score: '700', time: '25'},
  {stt: 9, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 10, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 11, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 12, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 13, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 14, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 15, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 16, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 17, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 18, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 19, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 20, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 21, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 22, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 23, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 24, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 25, nickname: 'Lê Văn Quang', score: '700', time: '25'},
  {stt: 26, nickname: 'Lê Văn Quang', score: '700', time: '25'},
]

export default usersData
